"""pet_settings timezone

Revision ID: 04e04f07c266
Revises: 7e03da47fc92
Create Date: 2026-06-28 15:01:18.776357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04e04f07c266'
down_revision: Union[str, None] = '7e03da47fc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_settings', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
