"""add commands

Revision ID: 48d3eb75b1c7
Revises: fb14289da05c
Create Date: 2026-06-28 02:51:08.439775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48d3eb75b1c7'
down_revision: Union[str, None] = 'fb14289da05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('command_id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_status'))
        batch_op.drop_index(batch_op.f('ix_commands_device_id'))

    op.drop_table('commands')
    # ### end Alembic commands ###
