"""device name

Revision ID: 698a81c8a55a
Revises: 04e04f07c266
Create Date: 2026-06-28 22:44:02.615414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '698a81c8a55a'
down_revision: Union[str, None] = '04e04f07c266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_config', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
