"""pet_shares

Revision ID: 7e03da47fc92
Revises: a9d0eeeeca83
Create Date: 2026-06-28 11:48:11.389540
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e03da47fc92'
down_revision: Union[str, None] = 'a9d0eeeeca83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_shares',
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pet_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_shares')
    # ### end Alembic commands ###
