"""pet_settings + geofence alert flags

Revision ID: a1952112a96a
Revises: 48d3eb75b1c7
Create Date: 2026-06-28 11:31:58.948439
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1952112a96a'
down_revision: Union[str, None] = '48d3eb75b1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_settings',
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('exit_enabled', sa.Boolean(), nullable=False),
    sa.Column('enter_enabled', sa.Boolean(), nullable=False),
    sa.Column('low_battery_enabled', sa.Boolean(), nullable=False),
    sa.Column('offline_enabled', sa.Boolean(), nullable=False),
    sa.Column('low_battery_threshold', sa.Integer(), nullable=True),
    sa.Column('quiet_start', sa.Integer(), nullable=True),
    sa.Column('quiet_end', sa.Integer(), nullable=True),
    sa.Column('tracking_paused', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pet_id')
    )
    with op.batch_alter_table('geofences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_on_exit', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('alert_on_enter', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('active_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active_end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_inside', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geofences', schema=None) as batch_op:
        batch_op.drop_column('last_inside')
        batch_op.drop_column('active_end')
        batch_op.drop_column('active_start')
        batch_op.drop_column('alert_on_enter')
        batch_op.drop_column('alert_on_exit')

    op.drop_table('pet_settings')
    # ### end Alembic commands ###
