"""device_config

Revision ID: a9d0eeeeca83
Revises: a1952112a96a
Create Date: 2026-06-28 11:41:01.964843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9d0eeeeca83'
down_revision: Union[str, None] = 'a1952112a96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('led_pattern', sa.String(), nullable=False),
    sa.Column('led_morse', sa.String(), nullable=False),
    sa.Column('report_interval_s', sa.Integer(), nullable=True),
    sa.Column('power_mode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_config')
    # ### end Alembic commands ###
