"""initial schema

Revision ID: f4706ed74db5
Revises: 
Create Date: 2026-06-28 02:14:17.540883
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4706ed74db5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('location_point_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('device_bindings',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('device_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_bindings_pet_id'), ['pet_id'], unique=False)

    op.create_table('device_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_events_device_id'), ['device_id'], unique=False)

    op.create_table('device_status',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('geofences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('consecutive_outside', sa.Integer(), nullable=False),
    sa.Column('open_alert_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofences_pet_id'), ['pet_id'], unique=False)

    op.create_table('location_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pet_id', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('heading', sa.Integer(), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('motion_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'seq', name='uq_device_seq')
    )
    with op.batch_alter_table('location_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_points_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_points_dt'), ['dt'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_points_pet_id'), ['pet_id'], unique=False)

    op.create_table('pets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pets_owner_id'), ['owner_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pets_owner_id'))

    op.drop_table('pets')
    with op.batch_alter_table('location_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_points_pet_id'))
        batch_op.drop_index(batch_op.f('ix_location_points_dt'))
        batch_op.drop_index(batch_op.f('ix_location_points_device_id'))

    op.drop_table('location_points')
    with op.batch_alter_table('geofences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofences_pet_id'))

    op.drop_table('geofences')
    op.drop_table('device_status')
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_events_device_id'))

    op.drop_table('device_events')
    with op.batch_alter_table('device_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_bindings_pet_id'))

    op.drop_table('device_bindings')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_pet_id'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
