"""add notification_deliveries

Revision ID: fb14289da05c
Revises: f4706ed74db5
Create Date: 2026-06-28 02:41:34.162553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb14289da05c'
down_revision: Union[str, None] = 'f4706ed74db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_alert_id'))

    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
